version: '2'
services:
    <%= baseName.toLowerCase() %>-mongodb:
        container_name: <%= baseName.toLowerCase() %>-mongodb
        image: mongo:3.2.3
        # volumes:
        #     - ~/volumes/jhipster/<%= baseName %>/mongodb/:/data/db/
        ports:
            - 27017:27017
